In [3]:
import math

In [1]:
def basic_sigmoid(x):
    s = 1/(1+math.exp(-x))
    return s

In [4]:
x = basic_sigmoid(-1)
x


0.2689414213699951

In [7]:
import numpy as np

x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [16]:
def np_sigmoid(x):
    s = 1/(1+np.exp(-x))
    return s

In [17]:
x = np_sigmoid(np.array([-1,2,3]))
x

array([0.26894142, 0.88079708, 0.95257413])

In [26]:
def grad_sig(x):
    sig = np_sigmoid(x)
    grad = sig*(1-sig)
    return grad

x = grad_sig(np.array([-1,2,3]))
x

array([0.19661193, 0.10499359, 0.04517666])

In [34]:
image = np.random.rand(3, 3, 2)
image

array([[[0.99666164, 0.98625945],
        [0.71872709, 0.09134612],
        [0.62017606, 0.27623441]],

       [[0.96904223, 0.02961433],
        [0.79050749, 0.53211341],
        [0.8217187 , 0.58824437]],

       [[0.173459  , 0.0341932 ],
        [0.71161036, 0.30928128],
        [0.65534545, 0.21232792]]])

In [33]:
def dim_1D(img):
    img = img.reshape(img.shape[0]*img.shape[1]*img.shape[2], 1)
    return img

image = dim_1D(image)
image

array([[0.74819418],
       [0.12824394],
       [0.1535513 ],
       [0.63419526],
       [0.13718007],
       [0.77671503],
       [0.03622564],
       [0.21836726],
       [0.2107273 ],
       [0.90150602],
       [0.07281708],
       [0.72306447],
       [0.91217786],
       [0.96889226],
       [0.49654963],
       [0.7399663 ],
       [0.82115896],
       [0.64596346]])

In [44]:
def norm_row(img):
    x_norm = np.linalg.norm(img, axis=1, keepdims = True)
    img  = img/x_norm
    return img

image = norm_row(image)
image

array([[[0.72409907, 0.95913624],
        [0.52217281, 0.08883401],
        [0.45057307, 0.26863766]],

       [[0.64758906, 0.03730898],
        [0.52827832, 0.67037162],
        [0.54913607, 0.741087  ]],

       [[0.1764893 , 0.09076898],
        [0.7240421 , 0.82101553],
        [0.66679425, 0.56364394]]])

In [45]:
img1 = np.array([[0,1000,4], 
                 [2,6,4]])
img1 = norm_row(img1)
img1

array([[0.        , 0.999992  , 0.00399997],
       [0.26726124, 0.80178373, 0.53452248]])