In [3]:
import math

In [1]:
def basic_sigmoid(x):
    s = 1/(1+math.exp(-x))
    return s

In [4]:
x = basic_sigmoid(-1)
x


0.2689414213699951

In [2]:
import numpy as np

x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [16]:
def np_sigmoid(x):
    s = 1/(1+np.exp(-x))
    return s

In [17]:
x = np_sigmoid(np.array([-1,2,3]))
x

array([0.26894142, 0.88079708, 0.95257413])

In [26]:
def grad_sig(x):
    sig = np_sigmoid(x)
    grad = sig*(1-sig)
    return grad

x = grad_sig(np.array([-1,2,3]))
x

array([0.19661193, 0.10499359, 0.04517666])

In [34]:
image = np.random.rand(3, 3, 2)
image

array([[[0.99666164, 0.98625945],
        [0.71872709, 0.09134612],
        [0.62017606, 0.27623441]],

       [[0.96904223, 0.02961433],
        [0.79050749, 0.53211341],
        [0.8217187 , 0.58824437]],

       [[0.173459  , 0.0341932 ],
        [0.71161036, 0.30928128],
        [0.65534545, 0.21232792]]])

In [33]:
def dim_1D(img):
    img = img.reshape(img.shape[0]*img.shape[1]*img.shape[2], 1)
    return img

image = dim_1D(image)
image

array([[0.74819418],
       [0.12824394],
       [0.1535513 ],
       [0.63419526],
       [0.13718007],
       [0.77671503],
       [0.03622564],
       [0.21836726],
       [0.2107273 ],
       [0.90150602],
       [0.07281708],
       [0.72306447],
       [0.91217786],
       [0.96889226],
       [0.49654963],
       [0.7399663 ],
       [0.82115896],
       [0.64596346]])

In [44]:
def norm_row(img):
    x_norm = np.linalg.norm(img, axis=1, keepdims = True)
    img  = img/x_norm
    return img

image = norm_row(image)
image

array([[[0.72409907, 0.95913624],
        [0.52217281, 0.08883401],
        [0.45057307, 0.26863766]],

       [[0.64758906, 0.03730898],
        [0.52827832, 0.67037162],
        [0.54913607, 0.741087  ]],

       [[0.1764893 , 0.09076898],
        [0.7240421 , 0.82101553],
        [0.66679425, 0.56364394]]])

In [45]:
img1 = np.array([[0,1000,4], 
                 [2,6,4]])
img1 = norm_row(img1)
img1

array([[0.        , 0.999992  , 0.00399997],
       [0.26726124, 0.80178373, 0.53452248]])

In [46]:
def softmax(x):
    x_exp = np.exp(x)
    
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    
    x = x_exp/x_sum
    
    return x

img2 = np.array([[9,2,5,0,0],
                [7,5,0,0,0]])
img2 = softmax(img2)
img2

array([[9.80897665e-01, 8.94462891e-04, 1.79657674e-02, 1.21052389e-04,
        1.21052389e-04],
       [8.78679856e-01, 1.18916387e-01, 8.01252314e-04, 8.01252314e-04,
        8.01252314e-04]])

In [78]:
import time

x1 = np.random.rand(1000000)
x2 = np.random.rand(1000000)

tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot += x1[i]*x2[i]
toc = time.process_time()
print("dot = "+str(dot)+"\n----Computation Time----" + str(1000*(toc-tic))+"ms")

dot = 249696.26141647133
----Computation Time----343.75ms


In [79]:
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print("dot = "+str(dot)+"\n----Computation Time----" + str(1000*(toc-tic))+"ms")

dot = 249696.26141645564
----Computation Time----0.0ms


In [5]:
y_ac = np.random.rand(10)
y_pred = np.random.rand(10)

print("L1 is", compute_l1(y_ac,y_pred))

L1 is 2.0487527823197724


In [4]:
def compute_l1(Y, Y_p):
    diff = abs(Y-Y_p)
    loss = np.sum(diff)
    return loss

yhat = np.array([1,1,1,1,1])
y = np.array([1,1,1,1,1])
print("L1 is", compute_l1(y,yhat))

L1 is 0


In [6]:
def compute_l2(y, yhat):
    diff = y-yhat
    loss = np.sum(diff**2)
    return loss

yhat = np.array([0.9,0.2,0.1,0.4,0.9])
y = np.array([1,0,0,1,1])
print("L2 is", compute_l2(y,yhat))


L2 is 0.43
